export const GET_RECIPES_REQUEST = "GET_RECIPES_REQUEST";
export const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";
export const GET_RECIPES_FAIL = "GET_RECIPES_FAIL";

export const GET_RECIPE_DETAILS_REQUEST = "GET_RECIPE_DETAILS_REQUEST";
export const GET_RECIPE_DETAILS_SUCCESS = "GET_RECIPE_DETAILS_SUCCESS";
export const GET_RECIPE_DETAILS_FAIL = "GET_RECIPE_DETAILS_FAIL";
export const GET_RECIPE_DETAILS_RESET = "GET_RECIPE_DETAILS_RESET";